name = "slm"
version = "0.2.1"

[dependencies]
stanza-toml = "StanzaOrg/stanza-toml|0.3.3"
semver      = "StanzaOrg/semver|0.1.3"
maybe-utils = "StanzaOrg/maybe-utils|0.1.2"
term-colors = "StanzaOrg/term-colors|0.1.0"
