name = "slm"
version = "0.2.3"

[dependencies]
stanza-toml = "StanzaOrg/stanza-toml|0.3.4"
semver      = "StanzaOrg/semver|0.1.4"
maybe-utils = "StanzaOrg/maybe-utils|0.1.3"
term-colors = "StanzaOrg/term-colors|0.1.1"
