name = "slm"
version = "0.6.9"

# note that the slm bootstrap.py script doesn't recursively resolve dependencies
# so define a flat list of all required dependencies here
[dependencies]
curl-static =              { git = "StanzaOrg/slm-curl",              version = "0.0.18" }
json-static =              { git = "StanzaOrg/slm-json",              version = "0.0.9" }
lang-utils-static =        { git = "StanzaOrg/slm-lang-utils",        version = "0.0.13" }
maybe-utils =              { git = "StanzaOrg/maybe-utils",           version = "0.1.6" }
semver      =              { git = "StanzaOrg/semver",                version = "0.1.8" }
slm-libarchive-static =    { git = "StanzaOrg/slm-libarchive",        version = "0.0.6" }
slm-libgit2-static =       { git = "StanzaOrg/slm-libgit2",           version = "0.0.3" }
slm-toml    =              { git = "StanzaOrg/slm-toml",              version = "0.4.3" }
term-colors =              { git = "StanzaOrg/term-colors",           version = "0.1.3" }
utils-file-system-static = { git = "StanzaOrg/slm-utils-file-system", version = "0.0.15" }

[dependencies.http_parser]
pkg="http_parser"
version="2.9.4"
type="conan"
options.shared = "False"
options.linux.fPIC = "True"
options.macos.fPIC = "True"

[dependencies.libarchive]
pkg="libarchive"
version="3.7.3"
type="conan"
options.shared = "False"
options.with_acl = "True"
options.with_bzip2 = "False"
options.with_cng = "False"
options.with_expat = "False"
options.with_iconv = "True"
options.with_libb2 = "False"
options.with_libxml2 = "False"
options.with_lz4 = "False"
options.with_lzma = "False"
options.with_lzo = "False"
options.with_mbedtls = "False"
options.with_nettle = "False"
options.with_openssl = "False"
options.with_pcre2 = "False"
options.with_pcreposix = "False"
options.with_xattr = "False"
options.with_zlib = "True"
options.with_zstd = "False"
options.linux.fPIC = "True"
options.macos.fPIC = "True"

[dependencies.libcurl]
pkg="libcurl"
version="8.6.0"
type="conan"
options.shared = "False"
options.with_brotli = "False"
options.with_c_ares = "False"
options.with_ca_bundle = "auto"
options.with_ca_fallback = "False"
options.with_ca_path = "auto"
options.with_cookies = "True"
options.with_crypto_auth = "True"
options.with_dict = "True"
options.with_docs = "False"
options.with_file = "True"
options.with_ftp = "True"
options.with_gopher = "True"
options.with_http = "True"
options.with_imap = "True"
options.with_ipv6 = "True"
options.with_largemaxwritesize = "False"
options.with_ldap = "False"
options.with_libgsasl = "False"
options.with_libidn = "False"
options.with_libpsl = "False"
options.with_librtmp = "False"
options.with_libssh2 = "False"
options.with_mqtt = "True"
options.with_nghttp2 = "False"
options.with_ntlm = "True"
options.with_ntlm_wb = "True"
options.with_pop3 = "True"
options.with_proxy = "True"
options.with_rtsp = "True"
options.with_smb = "True"
options.with_smtp = "True"
options.with_ssl = "openssl"
options.with_symbol_hiding = "False"
options.with_telnet = "True"
options.with_tftp = "True"
options.with_threaded_resolver = "True"
options.with_unix_sockets = "True"
options.with_verbose_debug = "True"
options.with_verbose_strings = "True"
options.with_zlib = "True"
options.with_zstd = "False"
options.linux.fPIC = "True"
options.linux.with_ssl = "openssl"
options.macos.fPIC = "True"
options.macos.with_ssl = "darwinssl"
options.windows.with_ssl = "schannel"
options.windows.with_unix_sockets = "False"

[dependencies.libgit2]
pkg="libgit2"
version="1.7.2"
type="conan"
options.shared = "False"
options.threadsafe = "True"
options.with_libssh2 = "True"
options.with_regex = "builtin"
options.linux.fPIC = "True"
options.linux.with_https = "openssl"
options.linux.with_ntlmclient = "False"
options.linux.with_sha1 = "openssl"
options.macos.fPIC = "True"
options.macos.with_https = "security"
options.macos.with_iconv = "False"
options.macos.with_ntlmclient = "False"
options.macos.with_sha1 = "commoncrypto"
options.windows.with_https = "winhttp"
options.windows.with_sha1 = "win32"

[dependencies.libiconv]
pkg="libiconv"
version="1.17"
type="conan"
options.shared = "False"
options.linux.fPIC = "True"
options.macos.fPIC = "True"

[dependencies.libssh2]
pkg="libssh2"
version="1.11.0"
type="conan"
options.shared = "False"
options.crypto_backend = "openssl"
options.enable_crypt_none = "False"
options.enable_debug_logging = "False"
options.enable_mac_none = "False"
options.with_zlib = "True"
options.linux.fPIC = "True"
options.macos.fPIC = "True"

[dependencies.openssl]
pkg="openssl"
version="3.2.1"
type="conan"
options.386 = "False"
options.enable_trace = "False"
options.enable_weak_ssl_ciphers = "False"
options.no_apps = "False"
options.no_aria = "False"
options.no_asm = "False"
options.no_async = "False"
options.no_autoload_config = "False"
options.no_bf = "False"
options.no_blake2 = "False"
options.no_camellia = "False"
options.no_cast = "False"
options.no_chacha = "False"
options.no_cms = "False"
options.no_comp = "False"
options.no_ct = "False"
options.no_deprecated = "False"
options.no_des = "False"
options.no_dgram = "False"
options.no_dh = "False"
options.no_dsa = "False"
options.no_dso = "False"
options.no_ec = "False"
options.no_ecdh = "False"
options.no_ecdsa = "False"
options.no_engine = "False"
options.no_filenames = "False"
options.no_fips = "False"
options.no_gost = "False"
options.no_idea = "False"
options.no_legacy = "False"
options.no_md2 = "True"
options.no_md4 = "False"
options.no_mdc2 = "False"
options.no_module = "False"
options.no_ocsp = "False"
options.no_pinshared = "False"
options.no_rc2 = "False"
options.no_rc4 = "False"
options.no_rc5 = "False"
options.no_rfc3779 = "False"
options.no_rmd160 = "False"
options.no_seed = "False"
options.no_sm2 = "False"
options.no_sm3 = "False"
options.no_sm4 = "False"
options.no_sock = "False"
options.no_srp = "False"
options.no_srtp = "False"
options.no_sse2 = "False"
options.no_ssl = "False"
options.no_ssl3 = "False"
options.no_stdio = "False"
options.no_threads = "False"
options.no_tls1 = "False"
options.no_ts = "False"
options.no_whirlpool = "False"
options.no_zlib = "False"
options.shared = "False"
options.tls_security_level = "2"
options.linux.fPIC = "True"
options.macos.fPIC = "True"
options.windows.capieng_dialog = "False"
options.windows.enable_capieng = "False"

[dependencies.zlib]
pkg="zlib"
version="1.3.1"
type="conan"
options.shared = "False"
options.linux.fPIC = "True"
options.macos.fPIC = "True"
